// Import the createSlice function from the Redux Toolkit package
import { createSlice } from "@reduxjs/toolkit";

// Define the initial state of the slice
const initialState = {
	mode: "dark", // Initial mode is set to 'dark'
	userId: "63701cc1f03239b7f700000e", // Initial user ID is set to '63701cc1f03239b7f700000e'
};

// Create a slice of the Redux store
export const globalSlice = createSlice({
	name: "global", // Name of the slice
	initialState, // Initial state of the slice
	reducers: {
		// Define the reducers to handle actions
		setMode: state => {
			// Toggle the mode between 'light' and 'dark'
			state.mode = state.mode === "light" ? "dark" : "light";
		},
	},
});

// Export the actions generated by the slice
export const { setMode } = globalSlice.actions;

// Export the reducer function to be included in the Redux store
export default globalSlice.reducer;
